#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libinstpatch
Version  : ff75961f1f489cbb05ab3e5f6737ace06c669e4a
Release  : 2
URL      : https://github.com/swami/libinstpatch/archive/ff75961f1f489cbb05ab3e5f6737ace06c669e4a.tar.gz
Source0  : https://github.com/swami/libinstpatch/archive/ff75961f1f489cbb05ab3e5f6737ace06c669e4a.tar.gz
Summary  : Instrument patch library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libinstpatch-lib = %{version}-%{release}
Requires: libinstpatch-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-gnome
BuildRequires : pkg-config
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(sndfile)
Patch1: build.patch

%description
#	libInstPatch
http://www.swamiproject.org
## 1. What is libInstPatch?
libInstPatch stands for lib-Instrument-Patch and is a library for processing digital sample based MIDI instrument "patch" files.
The types of files libInstPatch supports are used for creating instrument sounds for wavetable synthesis. libInstPatch provides
an object framework (based on GObject) to load patch files into, which can then be edited, converted, compressed and saved.

%package dev
Summary: dev components for the libinstpatch package.
Group: Development
Requires: libinstpatch-lib = %{version}-%{release}
Provides: libinstpatch-devel = %{version}-%{release}
Requires: libinstpatch = %{version}-%{release}
Requires: libinstpatch = %{version}-%{release}

%description dev
dev components for the libinstpatch package.


%package lib
Summary: lib components for the libinstpatch package.
Group: Libraries
Requires: libinstpatch-license = %{version}-%{release}

%description lib
lib components for the libinstpatch package.


%package license
Summary: license components for the libinstpatch package.
Group: Default

%description license
license components for the libinstpatch package.


%prep
%setup -q -n libinstpatch-ff75961f1f489cbb05ab3e5f6737ace06c669e4a
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560107889
mkdir -p clr-build
pushd clr-build
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DINTROSPECTION_ENABLED=off
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1560107889
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libinstpatch
cp COPYING %{buildroot}/usr/share/package-licenses/libinstpatch/COPYING
pushd clr-build
%make_install
popd
## install_append content
mv %{buildroot}/usr/lib6464 %{buildroot}/usr/lib64
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libinstpatch-0/libinstpatch/IpatchBase.h
/usr/include/libinstpatch-0/libinstpatch/IpatchContainer.h
/usr/include/libinstpatch-0/libinstpatch/IpatchConvert_DLS2.h
/usr/include/libinstpatch-0/libinstpatch/IpatchConvert_Gig.h
/usr/include/libinstpatch-0/libinstpatch/IpatchConvert_SF2.h
/usr/include/libinstpatch-0/libinstpatch/IpatchConvert_SLI.h
/usr/include/libinstpatch-0/libinstpatch/IpatchConverter.h
/usr/include/libinstpatch-0/libinstpatch/IpatchConverterSF2VoiceCache.h
/usr/include/libinstpatch-0/libinstpatch/IpatchDLS2.h
/usr/include/libinstpatch-0/libinstpatch/IpatchDLS2Conn.h
/usr/include/libinstpatch-0/libinstpatch/IpatchDLS2Info.h
/usr/include/libinstpatch-0/libinstpatch/IpatchDLS2Inst.h
/usr/include/libinstpatch-0/libinstpatch/IpatchDLS2Region.h
/usr/include/libinstpatch-0/libinstpatch/IpatchDLS2Sample.h
/usr/include/libinstpatch-0/libinstpatch/IpatchDLSFile.h
/usr/include/libinstpatch-0/libinstpatch/IpatchDLSReader.h
/usr/include/libinstpatch-0/libinstpatch/IpatchDLSWriter.h
/usr/include/libinstpatch-0/libinstpatch/IpatchFile.h
/usr/include/libinstpatch-0/libinstpatch/IpatchGig.h
/usr/include/libinstpatch-0/libinstpatch/IpatchGigDimension.h
/usr/include/libinstpatch-0/libinstpatch/IpatchGigEffects.h
/usr/include/libinstpatch-0/libinstpatch/IpatchGigFile.h
/usr/include/libinstpatch-0/libinstpatch/IpatchGigInst.h
/usr/include/libinstpatch-0/libinstpatch/IpatchGigRegion.h
/usr/include/libinstpatch-0/libinstpatch/IpatchGigSample.h
/usr/include/libinstpatch-0/libinstpatch/IpatchGigSubRegion.h
/usr/include/libinstpatch-0/libinstpatch/IpatchItem.h
/usr/include/libinstpatch-0/libinstpatch/IpatchIter.h
/usr/include/libinstpatch-0/libinstpatch/IpatchList.h
/usr/include/libinstpatch-0/libinstpatch/IpatchParamProp.h
/usr/include/libinstpatch-0/libinstpatch/IpatchPaste.h
/usr/include/libinstpatch-0/libinstpatch/IpatchRange.h
/usr/include/libinstpatch-0/libinstpatch/IpatchRiff.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2File.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2Gen.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2GenItem.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2IZone.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2Inst.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2Mod.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2ModItem.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2ModList.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2PZone.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2Preset.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2Reader.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2Sample.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2VoiceCache.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2VoiceCache_DLS.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2VoiceCache_Gig.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2VoiceCache_SF2.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2VoiceCache_SLI.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2VoiceCache_VBank.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2Writer.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSF2Zone.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSLI.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSLIFile.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSLIInst.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSLIReader.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSLISample.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSLIWriter.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSLIZone.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSample.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleData.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleList.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleStore.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleStoreCache.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleStoreFile.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleStoreRam.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleStoreRom.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleStoreSndFile.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleStoreSplit24.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleStoreSwap.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleStoreVirtual.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSampleTransform.h
/usr/include/libinstpatch-0/libinstpatch/IpatchSndFile.h
/usr/include/libinstpatch-0/libinstpatch/IpatchTypeProp.h
/usr/include/libinstpatch-0/libinstpatch/IpatchUnit.h
/usr/include/libinstpatch-0/libinstpatch/IpatchUnit_DLS.h
/usr/include/libinstpatch-0/libinstpatch/IpatchUnit_SF2.h
/usr/include/libinstpatch-0/libinstpatch/IpatchUnit_generic.h
/usr/include/libinstpatch-0/libinstpatch/IpatchVBank.h
/usr/include/libinstpatch-0/libinstpatch/IpatchVBankInst.h
/usr/include/libinstpatch-0/libinstpatch/IpatchVBankRegion.h
/usr/include/libinstpatch-0/libinstpatch/IpatchVirtualContainer.h
/usr/include/libinstpatch-0/libinstpatch/IpatchVirtualContainer_types.h
/usr/include/libinstpatch-0/libinstpatch/IpatchXml.h
/usr/include/libinstpatch-0/libinstpatch/IpatchXmlObject.h
/usr/include/libinstpatch-0/libinstpatch/builtin_enums.h
/usr/include/libinstpatch-0/libinstpatch/compat.h
/usr/include/libinstpatch-0/libinstpatch/libinstpatch.h
/usr/include/libinstpatch-0/libinstpatch/misc.h
/usr/include/libinstpatch-0/libinstpatch/sample.h
/usr/include/libinstpatch-0/libinstpatch/util.h
/usr/include/libinstpatch-0/libinstpatch/version.h
/usr/lib64/libinstpatch.so
/usr/lib64/pkgconfig/libinstpatch.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libinstpatch.so.0
/usr/lib64/libinstpatch.so.0.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libinstpatch/COPYING
